language: python
python:
  - "2.7"
install:
  # Build/test dependencies
  - pip install -r requirements-dev.txt --use-mirrors
  # Install Julython
  - pip install -e .
script:
  - fab test:skip_js=True
notifications:
  irc:
    channels: "irc.freenode.org#julython"
    on_success: change
    on_failure: change
  email: false