application: julython
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on
- remote_api: on
- admin_redirect: on
- django_wsgi: on
- deferred: on

env_variables:
  DJANGO_SETTINGS_MODULE: 'july.settings'

libraries:
- name: django
  version: "1.3"

handlers:
- url: /static
  static_dir: july/static_root
