application: julython
version: 1
runtime: python27
api_version: 1
threadsafe: true

env_variables:
  DJANGO_SETTINGS_MODULE: 'july.settings'

builtins:
- appstats: on
- remote_api: on
- admin_redirect: on
- django_wsgi: on
- deferred: on

inbound_services:
- warmup
- channel_presence

libraries:
- name: django
  version: "latest"
- name: webapp2
  version: "latest"

handlers:
- url: /static
  static_dir: july/static_root

- url: /(favicon.ico|robots.txt)
  static_files: july/static_root/\1
  upload: /static/(.*)

- url: /__cron__.*
  script: july.cron.app
  login: admin

- url: /_ah/channel/(connected|disconnected)/
  script: july.channel.app

- url: /api.*
  script: july.api.app

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?assets/.*
